#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../lib";
use Data::Dumper;
use Carp;
use NAC::IBWAPI;
use strict;

my $wapi = NAC::IBWAPI->new();

my $obj_ref = $wapi->GET( $IB_NETWORK, { $IB_RETURN_FIELDS => [ $IB_RETURN_FIELD_EXTATTRS,$IB_RETURN_FIELD_OPTIONS ], } );

# my $obj_ref = NAC::IBWAPI::GET( $IB_NETWORK, { $IB_RETURN_FIELDS => [ $IB_RETURN_FIELD_EXTATTRS,$IB_RETURN_FIELD_OPTIONS ], } );
# my $obj_ref = NAC::IBWAPI->GET( $IB_NETWORK, { $IB_RETURN_FIELDS => [ $IB_RETURN_FIELD_EXTATTRS,$IB_RETURN_FIELD_OPTIONS ], } );

# my $obj_ref = NAC::IBWAPI::Network->GET( $IB_NETWORK, { $IB_RETURN_FIELDS => [ $IB_RETURN_FIELD_EXTATTRS,$IB_RETURN_FIELD_OPTIONS ], } );

