#!/usr/bin/perl

use FindBin;
use lib "$FindBin::Bin/../lib";
use Data::Dumper;
use Carp;
use NAC::IBWAPI;
use strict;

my $wapi = NAC::IBWAPI->new();

$wapi->GET( { $IB_OBJECT => $IB_OBJECT_NETWORK, $IB_RETURN_FIELDS => [ $IB_RETURN_FIELD_EXTATTRS,$IB_RETURN_FIELD_OPTIONS ], } );


