
SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `naceventlog`
--

-- --------------------------------------------------------

--
-- Table structure for table `eventlog`
--

CREATE TABLE IF NOT EXISTS `eventlog` (
  `eventlogid` int(11) NOT NULL AUTO_INCREMENT,
  `eventtime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `eventtype` enum('EVENT_START','EVENT_STOP','EVENT_ACCT_STOP','EVENT_ACCT_START','EVENT_AUTH_CLEAR','EVENT_AUTH_BLOCK','EVENT_AUTH_CHALLENGE','EVENT_AUTH_GUEST','EVENT_AUTH_MAC','EVENT_AUTH_PORT','EVENT_AUTH_VOICE','EVENT_AUTH_NAK','EVENT_CHALLENGE_ERR','EVENT_CIDR_ADD','EVENT_CIDR_DEL','EVENT_CLASS_ADD','EVENT_CLASS_DEL','EVENT_CLASS_UPD','EVENT_DB_ERR','EVENT_DB_WARN','EVENT_FILTER_ADD','EVENT_FILTER_DEL','EVENT_FIXEDIP_ADD','EVENT_FIXEDIP_DEL','EVENT_FIXEDIP_UPD','EVENT_MAC2CLASS_ADD','EVENT_MAC2CLASS_DEL','EVENT_MAC2CLASS_UPD','EVENT_MAC_ADD','EVENT_MAC_DEL','EVENT_MAC_UPD','EVENT_MAGIC_PORT','EVENT_MEMCACHE_ERR','EVENT_MEMCACHE_WARN','EVENT_LOC_ADD','EVENT_LOC_DEL','EVENT_LOC_UPD','EVENT_PORT_ADD','EVENT_PORT_DEL','EVENT_PORT2CLASS_ADD','EVENT_PORT2CLASS_DEL','EVENT_PORT2CLASS_UPD','EVENT_SWITCH_ADD','EVENT_SWITCH_DEL','EVENT_SWITCH_UPD','EVENT_SWITCHPORT_ADD','EVENT_SWITCHPORT_DEL','EVENT_SWITCH2VLAN_ADD','EVENT_SWITCH2VLAN_DEL','EVENT_TEMPLATE_ADD','EVENT_TEMPLATE_DEL','EVENT_TEMPLATE2VLANGROUP_ADD','EVENT_TEMPLATE2VLANGROUP_DEL','EVENT_VLAN_ADD','EVENT_VLAN_DEL','EVENT_VLANGROUP_ADD','EVENT_VLANGROUP_DEL','EVENT_VLANGROUP2VLAN_ADD','EVENT_VLANGROUP2VLAN_DEL','EVENT_NOLOCATION','EVENT_SMTP_FAIL','EVENT_LOGIC_FAIL','EVENT_EVAL_FAIL','EVENT_FUNC_FAIL','EVENT_ERR','EVENT_WARN','EVENT_NOTICE','EVENT_INFO','EVENT_DEBUG','EVENT_FATAL','EVENT_DISTRESS') NOT NULL,
  `userid` int(11) DEFAULT NULL,
  `hostname` varchar(64) DEFAULT NULL,
  `classid` int(11) DEFAULT NULL,
  `locationid` int(11) DEFAULT NULL,
  `macid` int(11) DEFAULT NULL,
  `mac2classid` int(11) DEFAULT NULL,
  `magicportid` int(11) DEFAULT NULL,
  `port2classid` int(11) DEFAULT NULL,
  `switchid` int(11) DEFAULT NULL,
  `switchportid` int(11) DEFAULT NULL,
  `switch2vlanid` int(11) DEFAULT NULL,
  `templateid` int(11) DEFAULT NULL,
  `template2vlangroupid` int(11) DEFAULT NULL,
  `vlangroupid` int(11) DEFAULT NULL,
  `vlangroup2vlanid` int(11) DEFAULT NULL,
  `vlanid` int(11) DEFAULT NULL,
  `ip` varchar(20) DEFAULT NULL,
  `eventtext` text,
  PRIMARY KEY (`eventlogid`),
  KEY `eventtype` (`eventtype`),
  KEY `eventtime` (`eventtime`),
  KEY `macid` (`macid`),
  KEY `switchportid` (`switchportid`),
  KEY `swichid` (`switchid`),
  KEY `userid` (`userid`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1;

